command: docker model config edit
short: Open the config file in your editor
long: |-
    Open the config file in the default editor.

    The editor is determined by the VISUAL or EDITOR environment variables,
    falling back to vi on Unix and notepad on Windows.
usage: docker model config edit
pname: docker model config
plink: docker_model_config.yaml
options:
    - option: file
      shorthand: f
      value_type: string
      description: use a specific config file
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
    - option: global
      value_type: bool
      default_value: "false"
      description: use the global (user-level) config file
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
    - option: system
      value_type: bool
      default_value: "false"
      description: use the system-wide config file
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
deprecated: false
hidden: false
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

