command: docker model config unset
short: Remove a config key
long: Remove a config key (and all its values) from the file.
usage: docker model config unset <key>
pname: docker model config
plink: docker_model_config.yaml
options:
    - option: file
      shorthand: f
      value_type: string
      description: use a specific config file
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
    - option: global
      value_type: bool
      default_value: "false"
      description: use the global (user-level) config file
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
    - option: system
      value_type: bool
      default_value: "false"
      description: use the system-wide config file
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
deprecated: false
hidden: false
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

