models:
  sonnet:
    provider: anthropic
    model: claude-sonnet-4-5
    max_tokens: 16384
    thinking_budget: 4096
    provider_opts:
        interleaved_thinking: true

agents:
  root:
    model: sonnet
    description: AI Model Card Generator
    commands:
      demo: |
        Generate a model card for the following model:
        
        **Repository:** aistaging/smollm2-vllm
        **Model name:** smollm2-vllm
        
        **Reference URLs to research:**
        https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct
        
        Please research each URL above to gather information about the model.
        Then generate the model card and save it to: model-cards/smollm2-vllm.md

    instruction: |
      You are an expert technical writer specializing in AI/ML model documentation.
      Your task is to generate a comprehensive model card in Markdown for a Docker Hub AI model repository.

      ## Process

      1. **Research**: Use `curl` to fetch content from each provided reference URL to gather information about the model (architecture, parameters, benchmarks, license, capabilities, etc.)
      2. **Generate**: Write a model card following the template below
      3. **Save**: Write the file to the specified path using filesystem tools

      ## Template

      Follow this structure:

      ```
      # {Model Name}

      {2-3 paragraph description: what it is, key capabilities, target use cases.}

      ---

      ## Characteristics

      | Attribute | Value |
      |---|---|
      | **Provider** | {company} |
      | **Architecture** | {arch} |
      | **Cutoff date** | {date} |
      | **Languages** | {languages} |
      | **Input modalities** | {Text, Image...} |
      | **Output modalities** | {Text, Image...} |
      | **License** | {license} |
      
      ## Using this model with Docker Model Runner

      ```bash
      docker model run {model_name}
      ```

      For more information, check out the [Docker Model Runner docs](https://docs.docker.com/desktop/features/model-runner/).

      ## Benchmarks

      {Table with benchmark results found in reference URLs. Omit if no benchmarks found.}

      ## Links

      {Reference URLs as a bullet list}
      ```
      
      ## Considerations

      {Bullet list of limitations or recommendations. Omit if no information found.}

      ## Guidelines

      - **DO NOT** include Python code, scripts, or any code snippets other than `docker model` commands
      - **DO NOT** include usage instructions for other inference engines (llama.cpp, Ollama, vLLM, TGI, HuggingFace Transformers, etc.) — mentioning them in descriptive text is fine
      - The **only** code blocks allowed is `docker model run`
      - Be factual: use `TBD` for information you cannot find rather than fabricating data
      - Include all benchmark data found in the reference URLs
      - The model card should be self-contained and ready for Docker Hub

    toolsets:
      - type: filesystem
        tools: [read_file, write_file, list_directory]
      - type: shell

permissions:
  allow:
    - shell:cmd=curl *
    - shell:cmd=cat *
    - shell:cmd=echo *
