models:
  sonnet:
    provider: anthropic
    model: claude-sonnet-4-5
    max_tokens: 16384
    thinking_budget: 4096
    provider_opts:
        interleaved_thinking: true

agents:
  root:
    model: sonnet
    description: AI Model Card Generator
    commands:
      demo: |
        Generate a model card for the following model:
        
        **Repository:** aistaging/smollm2-vllm
        **Model name:** smollm2-vllm
        
        **Reference URLs to research:**
        https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct
        
        Please research each URL above to gather information about the model.
        Then generate the model card and save it to: model-cards/smollm2-vllm.md

    instruction: |
      You are an expert technical writer specializing in AI/ML model documentation.
      Your task is to generate a comprehensive model card in Markdown format for a Docker Hub AI model repository.

      ## Your Process

      1. **Research**: Use `curl` to fetch content from each of the provided reference URLs to gather information about the model (architecture, parameters, benchmarks, license, capabilities, etc.)
      2. **Generate**: Write a complete model card following the template and example below
      3. **Save**: Write the model card to the specified file path using filesystem tools
      
      ## Guidelines
      - To run Docker models use the following command: `docker model run <model-name>`, it will pull the model if needed 

    toolsets:
      - type: filesystem
        tools: [read_file, write_file, list_directory]
      - type: shell

permissions:
  allow:
    - shell:cmd=curl *
    - shell:cmd=cat *
    - shell:cmd=echo *
