/*
 * handler_bridge.c — C helper for the Go→Rust handler callback.
 *
 * This file is compiled by CGo as part of the router package.  It includes
 * _cgo_export.h (generated by CGo, contains the correct prototype for
 * goHandleRequest) so we can safely take its address.
 *
 * We cannot do this in the Go file's inline C preamble because the preamble
 * is compiled before _cgo_export.h exists; only a separate .c file can
 * include it.
 */

#include "_cgo_export.h"
#include "dmr_router.h"
#include <stdlib.h>
#include <string.h>

/* Return goHandleRequest as a DmrHandlerFn.  Called from Go via CGo. */
DmrHandlerFn dmr_go_handler_fn(void) {
    return (DmrHandlerFn)goHandleRequest;
}

/* Allocate n bytes via the C heap.  Rust frees with its global allocator
 * (which also calls free(3)).  Called from Go via CGo. */
uint8_t *dmr_c_alloc(size_t n) {
    return (uint8_t *)malloc(n);
}
