//go:build cgo

package router

// handler.go — CGo bridge that lets the Rust router call Go's http.Handler
// directly, with full streaming support.
//
// The streaming protocol (mirrors dmr_router.h):
//   - Rust sets resp.stream_ctx to a raw *ChunkSender before calling Go.
//   - Go calls dmr_write_chunk(stream_ctx, data, len) for each Write/Flush.
//   - Go calls dmr_close_stream(stream_ctx) after ServeHTTP returns.
//   - Rust reads from the mpsc receiver and forwards chunks to the axum client.
//
// Memory contract for headers:
//   - resp.header_block is allocated by Go via C.malloc; Rust frees it.

/*
#include "dmr_router.h"
#include <string.h>

// dmr_go_handler_fn and dmr_c_alloc are defined in handler_bridge.c which
// includes _cgo_export.h (generated by CGo) so it can safely reference
// goHandleRequest without a conflicting forward declaration.
DmrHandlerFn dmr_go_handler_fn(void);
uint8_t *dmr_c_alloc(size_t n);
*/
import "C"

import (
	"bytes"
	"fmt"
	"net/http"
	"strings"
	"sync/atomic"
	"unsafe"
)

// globalHandler is set once by RegisterHandler and read on every request.
var globalHandler atomic.Value // stores http.Handler

// RegisterHandler stores h as the in-process backend and returns the
// (handlerFn, handlerCtx) pair to embed in DmrRouterConfig.
// Must be called before router.Start.
func RegisterHandler(h http.Handler) (handlerFn unsafe.Pointer, handlerCtx unsafe.Pointer) {
	globalHandler.Store(h)
	return unsafe.Pointer(C.dmr_go_handler_fn()), nil
}

// streamingResponseWriter implements http.ResponseWriter and http.Flusher.
// Each Write call pushes a chunk to Rust via dmr_write_chunk; Flush is a no-op
// since dmr_write_chunk sends immediately.
type streamingResponseWriter struct {
	header      http.Header
	statusCode  int
	wroteHeader bool
	resp        *C.DmrResponse
}

func newStreamingResponseWriter(resp *C.DmrResponse) *streamingResponseWriter {
	return &streamingResponseWriter{
		header:     make(http.Header),
		statusCode: http.StatusOK,
		resp:       resp,
	}
}

func (w *streamingResponseWriter) Header() http.Header {
	return w.header
}

func (w *streamingResponseWriter) WriteHeader(code int) {
	if w.wroteHeader {
		return
	}
	w.wroteHeader = true
	w.statusCode = code

	// Serialise headers into flat "Name: Value\0…\0" block and store in resp.
	var hdrBuf strings.Builder
	for name, vals := range w.header {
		for _, val := range vals {
			fmt.Fprintf(&hdrBuf, "%s: %s", name, val)
			hdrBuf.WriteByte(0)
		}
	}
	hdrBuf.WriteByte(0) // end-of-list sentinel
	hdrBytes := []byte(hdrBuf.String())

	w.resp.status = C.uint16_t(code)
	if len(hdrBytes) > 0 {
		p := C.dmr_c_alloc(C.size_t(len(hdrBytes)))
		C.memcpy(unsafe.Pointer(p), unsafe.Pointer(&hdrBytes[0]), C.size_t(len(hdrBytes)))
		w.resp.header_block.ptr = p
		w.resp.header_block.len = C.size_t(len(hdrBytes))
	}
}

func (w *streamingResponseWriter) Write(data []byte) (int, error) {
	if !w.wroteHeader {
		w.WriteHeader(http.StatusOK)
	}
	if len(data) == 0 {
		return 0, nil
	}
	rc := C.dmr_write_chunk(w.resp.stream_ctx, (*C.uint8_t)(unsafe.Pointer(&data[0])), C.size_t(len(data)))
	if rc != 0 {
		return 0, fmt.Errorf("dmr_write_chunk: client disconnected")
	}
	return len(data), nil
}

// Flush implements http.Flusher. Chunks are sent immediately on Write, so
// this is a no-op — but it must exist so handlers that type-assert to
// http.Flusher (like the model pull progress handler) don't fail.
func (w *streamingResponseWriter) Flush() {}

// goHandleRequest is invoked by Rust (via the C shim) for every proxied
// inference request.  It reconstructs an http.Request from the DmrRequest
// and dispatches it to the registered http.Handler using the streaming writer.
//
//export goHandleRequest
func goHandleRequest(_ unsafe.Pointer, req *C.DmrRequest, resp *C.DmrResponse) {
	h, ok := globalHandler.Load().(http.Handler)
	if !ok || h == nil {
		resp.status = 503
		C.dmr_close_stream(resp.stream_ctx)
		return
	}

	// ── Reconstruct http.Request ─────────────────────────────────────────

	method := C.GoString(req.method)
	path := C.GoString(req.path)

	var bodyReader *bytes.Reader
	if req.body.ptr != nil && req.body.len > 0 {
		bodyBytes := C.GoBytes(unsafe.Pointer(req.body.ptr), C.int(req.body.len))
		bodyReader = bytes.NewReader(bodyBytes)
	} else {
		bodyReader = bytes.NewReader(nil)
	}

	httpReq, err := http.NewRequest(method, path, bodyReader)
	if err != nil {
		resp.status = 400
		C.dmr_close_stream(resp.stream_ctx)
		return
	}

	// Parse flat "Name: Value\0…\0" header block.
	if req.header_block.ptr != nil && req.header_block.len > 0 {
		raw := C.GoBytes(unsafe.Pointer(req.header_block.ptr), C.int(req.header_block.len))
		pos := 0
		for pos < len(raw) {
			end := bytes.IndexByte(raw[pos:], 0)
			if end < 0 {
				break
			}
			end += pos
			if end == pos {
				break
			}
			entry := string(raw[pos:end])
			if sep := strings.Index(entry, ": "); sep >= 0 {
				httpReq.Header.Add(entry[:sep], entry[sep+2:])
			}
			pos = end + 1
		}
	}

	// ── Invoke Go handler with streaming writer ───────────────────────────

	w := newStreamingResponseWriter(resp)
	h.ServeHTTP(w, httpReq)

	// Ensure WriteHeader was called even if the handler wrote nothing.
	if !w.wroteHeader {
		w.WriteHeader(http.StatusOK)
	}

	// Signal end-of-body to Rust (drops the mpsc Sender, closing the channel).
	C.dmr_close_stream(resp.stream_ctx)
}
