name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Verify vendor/ is not present
        run: stat vendor && exit 1 || exit 0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version: 1.24.2
          cache: true

      - name: Check go mod tidy
        run: |
          go mod tidy
          go mod tidy -C cmd/cli
          go work sync
          git diff --exit-code go.mod go.sum cmd/cli/go.mod cmd/cli/go.sum go.work go.work.sum

      - name: Run tests with race detection
        run: go test -race ./...

      - name: validate
        run: make validate

      - name: model-distribution # TODO: Create a single Makefile for the monorepo
        run: make -C ./pkg/distribution/ all
