name: Validate model-cli

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'v[0-9]*'
    tags:
      - 'v*'
    paths:
      - 'cmd/cli/**'
      - '.github/workflows/cli-validate.yml'
  pull_request:
    paths:
      - 'cmd/cli/**'
      - '.github/workflows/cli-validate.yml'

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      targets: ${{ steps.generate.outputs.targets }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      -
        name: List targets
        id: generate
        uses: docker/bake-action/subaction/list-targets@3acf805d94d93a86cce4ca44798a76464a75b88c
        with:
          files: ./cmd/cli/docker-bake.hcl
          target: validate

  validate:
    runs-on: ubuntu-24.04
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare.outputs.targets) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      -
        name: Validate
        uses: docker/bake-action@v6
        with:
          files: ./cmd/cli/docker-bake.hcl
          targets: ${{ matrix.target }}
