name: Validate model-cli

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'v[0-9]*'
    tags:
      - 'v*'
    paths:
      - 'cmd/cli/**'
      - '.github/workflows/cli-validate.yml'
  pull_request:
    paths:
      - 'cmd/cli/**'
      - '.github/workflows/cli-validate.yml'

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      -
        name: Generate matrix
        id: generate
        uses: docker/bake-action/subaction/matrix@018cb6412ab401ebaa809aa5f85966b74628600f
        with:
          files: ./cmd/cli/docker-bake.hcl
          target: validate

  validate:
    runs-on: ubuntu-24.04
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4
        with:
          buildkitd-flags: --debug
      -
        name: Validate
        uses: docker/bake-action@018cb6412ab401ebaa809aa5f85966b74628600f # v7
        with:
          files: ./cmd/cli/docker-bake.hcl
          targets: ${{ matrix.target }}
